/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package megatherium.ui;

import megatherium.application.Application;
import megatherium.communicator.data.ILoginInformation;
import megatherium.communicator.data.Platform;
import megatherium.data.store.PlatformStore;
import megatherium.data.store.Stores;
import megatherium.event.EventManager;
import megatherium.event.IEventListener;

/**
 *
 * @author marti_000
 */
public class AccountCreatePanel extends EventPanel implements IEventListener {
	private ILoginInformation loginInformation;

	/**
	 * Creates new form AccountCreatePanel
	 */
	public AccountCreatePanel() {
		initComponents();
		
		EventManager.getInstance().addListener("megatherium.ui.account.create.show", this);
		
	}
	
	
	/**
	 * Resets the inputs.
	 */
	public void reset() {
		this.alias.setText("");
	}
	
	/**
	 * Displays this panel.
	 */
	public void display() {
		System.out.println("Display!");
		((PlatformComboBoxModel) this.platform.getModel()).removeAllElements();
		for (Platform platform : ((PlatformStore) Stores.getInstance().getStore("platformStore")).getItems())
			((PlatformComboBoxModel) this.platform.getModel()).addElement(platform);
	}
	
	/**
	 * Sets the login information.
	 * 
	 * @param loginInformation the login information
	 */
	public void setLoginInformation(ILoginInformation loginInformation) {
		System.err.println("Set login information: "+loginInformation.getClass().getCanonicalName());
		this.loginInformation = loginInformation;
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        platform = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        alias = new javax.swing.JTextField();
        addLoginInformation = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setText("Plattform:");

        platform.setModel(new PlatformComboBoxModel());
        platform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platformActionPerformed(evt);
            }
        });

        jLabel2.setText("Alias:");

        addLoginInformation.setText("Kontoinformationen");
        addLoginInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoginInformationActionPerformed(evt);
            }
        });

        saveButton.setText("Speichern");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(addLoginInformation))
                            .addComponent(alias)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLoginInformation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLoginInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoginInformationActionPerformed
		EventManager.getInstance().fireEvent("megatherium.ui.account.login.information.show", this.platform.getSelectedItem());
    }//GEN-LAST:event_addLoginInformationActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		EventManager.getInstance().fireEvent("megatherium.data.account.create", ((Platform) this.platform.getSelectedItem()).getName(), this.alias.getText(), (ILoginInformation) this.loginInformation);
		this.alias.setText("");
		EventManager.getInstance().fireEvent("megatherium.ui.account.list.show");
		
    }//GEN-LAST:event_saveButtonActionPerformed

    private void platformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platformActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		EventManager.getInstance().fireEvent("megatherium.ui.account.list.show");
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLoginInformation;
    private javax.swing.JTextField alias;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox platform;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

	@Override
	public void execute(Object[] parameters) {
		this.display();
	}
	
}
