/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package megatherium.ui;

import megatherium.application.Application;
import megatherium.communicator.data.ILoginInformation;
import megatherium.communicator.data.Platform;
import megatherium.data.store.PlatformStore;
import megatherium.data.store.Stores;
import megatherium.event.EventManager;
import megatherium.event.IEventListener;

/**
 *
 * @author marti_000
 */
public class AccountCreatePanel extends EventPanel implements IEventListener {
	private ILoginInformation loginInformation;

	/**
	 * Creates new form AccountCreatePanel
	 */
	public AccountCreatePanel() {
		initComponents();
		
		EventManager.getInstance().addAfterListener("megatherium.ui.account.create.show", this);
	}
	
	/**
	 * Displays this panel.
	 */
	public void display() {
		((PlatformComboBoxModel) this.platform.getModel()).removeAllElements();
		for (Platform platform : ((PlatformStore) Stores.getInstance().getStore("platformStore")).getItems())
			((PlatformComboBoxModel) this.platform.getModel()).addElement(platform);
	}
	
	/**
	 * Sets the login information.
	 * 
	 * @param loginInformation the login information
	 */
	public void setLoginInformation(ILoginInformation loginInformation) {
		this.loginInformation = loginInformation;
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        platform = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        alias = new javax.swing.JTextField();
        addLoginInformation = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Plattform:");

        platform.setModel(new PlatformComboBoxModel());

        jLabel2.setText("Alias:");

        addLoginInformation.setText("Kontoinformationen");
        addLoginInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoginInformationActionPerformed(evt);
            }
        });

        jButton2.setText("Speichern");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Abbrechen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(addLoginInformation))
                            .addComponent(alias)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLoginInformation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLoginInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoginInformationActionPerformed
		EventManager.getInstance().fireEvent("megatherium.ui.account.login.information.show", new Object[] {this.platform.getSelectedItem()});
    }//GEN-LAST:event_addLoginInformationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		EventManager.getInstance().fireEvent("megatherium.data.account.create", new Object[] {this.platform.getSelectedItem(), this.alias.getText(), this.loginInformation});
		this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLoginInformation;
    private javax.swing.JTextField alias;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox platform;
    // End of variables declaration//GEN-END:variables

	@Override
	public void execute(Object[] parameters) {
		this.display();
	}
	
}
